stages:
  download_data:
    cmd: python src/download_data.py
    deps:
    - src/download_data.py
    outs:
    - data/raw/iris.csv

  clean_data:
    cmd: python src/clean_data.py
    deps:
    - src/clean_data.py
    - data/raw/iris.csv
    outs:
    - data/processed/iris_processed.csv

  train_model:
    cmd: python src/train_model.py
    deps:
    - data/processed/iris_processed.csv
    - src/train_model.py
    metrics:
    - models/metrics_train_model.json:
        cache: false

